export const cartActionTypes = {
	ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    SUBTRACT_ITEM: 'SUBTRACT_ITEM',
    SAVE_CART: 'SAVE_CART',
    CHECKOUT: 'CHECKOUT',
    CALC_SUBTOTAL: 'CALC_SUBTOTAL',
    CLEAR_CART: 'CLEAR_CART',
    POPULATE_CART: 'POPULATE_CART',
};
